// Single source of truth for IPC channel names.
//
// Main, preload, and renderer all reference values from this map instead of typing the
// channel string literally, so a typo at any site is a compile-time error and a renamed
// channel is a single edit. See CONTEXT.md for the IPC seam vocabulary.
export const CHANNELS = {
  account: {
    get: "account:get",
    update: "account:update",
  },
  app: {
    flushAndQuit: "app:flushAndQuit",
    fullscreenChange: "app:fullscreenChange",
    setMenuBarIconVisible: "app:setMenuBarIconVisible",
    setUnsavedChanges: "app:setUnsavedChanges",
  },
  appSettings: {
    get: "appSettings:get",
    update: "appSettings:update",
  },
  automations: {
    create: "automations:create",
    delete: "automations:delete",
    execute: "automations:execute",
    getAll: "automations:getAll",
    getAvailableActions: "automations:getAvailableActions",
    getById: "automations:getById",
    getRunHistory: "automations:getRunHistory",
    update: "automations:update",
  },
  browser: {
    attach: "browser:attach",
    back: "browser:back",
    deleteCapture: "browser:deleteCapture",
    destroy: "browser:destroy",
    detach: "browser:detach",
    forward: "browser:forward",
    getNavState: "browser:getNavState",
    navState: "browser:navState",
    navigate: "browser:navigate",
    reload: "browser:reload",
    selectModeChanged: "browser:selectModeChanged",
    selection: "browser:selection",
    setBounds: "browser:setBounds",
    setSelectMode: "browser:setSelectMode",
    setVisible: "browser:setVisible",
    stop: "browser:stop",
  },
  collections: {
    addSource: "collections:addSource",
    archive: "collections:archive",
    create: "collections:create",
    get: "collections:get",
    list: "collections:list",
    listSources: "collections:listSources",
    remove: "collections:remove",
    removeSource: "collections:removeSource",
    unarchive: "collections:unarchive",
    update: "collections:update",
  },
  connections: {
    checkCredentials: "connections:checkCredentials",
    deleteResource: "connections:deleteResource",
    getAsanaProjects: "connections:getAsanaProjects",
    getByProvider: "connections:getByProvider",
    getGithubRepos: "connections:getGithubRepos",
    getGitlabProjects: "connections:getGitlabProjects",
    getJiraProjects: "connections:getJiraProjects",
    getLinearTeams: "connections:getLinearTeams",
    getSelectedResources: "connections:getSelectedResources",
    getSentryProjects: "connections:getSentryProjects",
    getSocketDevOrganizations: "connections:getSocketDevOrganizations",
    getTrelloBoards: "connections:getTrelloBoards",
    githubDevicePoll: "connections:githubDevicePoll",
    githubDeviceStart: "connections:githubDeviceStart",
    listStates: "connections:listStates",
    removeResource: "connections:removeResource",
    revoke: "connections:revoke",
    saveCredentials: "connections:saveCredentials",
    saveResources: "connections:saveResources",
    updateState: "connections:updateState",
  },
  documents: {
    sign: "documents:sign",
  },
  entities: {
    create: "entities:create",
    delete: "entities:delete",
    getAll: "entities:getAll",
    getById: "entities:getById",
    search: "entities:search",
    update: "entities:update",
  },
  fileExplorer: {
    getPathInfo: "fileExplorer:getPathInfo",
    listDir: "fileExplorer:listDir",
    readDirectory: "fileExplorer:readDirectory",
    readDirectoryShallow: "fileExplorer:readDirectoryShallow",
    readFile: "fileExplorer:readFile",
    readFileText: "fileExplorer:readFileText",
    saveFileAs: "fileExplorer:saveFileAs",
    searchFiles: "fileExplorer:searchFiles",
    writeFileText: "fileExplorer:writeFileText",
  },
  // NOTE: there is deliberately no `git` namespace — the git module is
  // main-process-internal. Renderer-triggered git effects are workspace/gitFlow
  // operations. See CONTEXT.md "git module".
  gitFlow: {
    getStatus: "gitFlow:getStatus",
    commit: "gitFlow:commit",
    push: "gitFlow:push",
    pull: "gitFlow:pull",
    createPr: "gitFlow:createPr",
    generateCommitMessage: "gitFlow:generateCommitMessage",
    generatePrBody: "gitFlow:generatePrBody",
    getPublishPreflight: "gitFlow:getPublishPreflight",
    publish: "gitFlow:publish",
  },
  guards: {
    checkPackage: "guards:checkPackage",
    checkPackages: "guards:checkPackages",
    getActiveGuard: "guards:getActiveGuard",
    getPackageScore: "guards:getPackageScore",
    scanWorkspace: "guards:scanWorkspace",
  },
  ssh: {
    discoverHosts: "ssh:discoverHosts",
    openTunnel: "ssh:openTunnel",
    closeTunnel: "ssh:closeTunnel",
  },
  backend: {
    describe: "backend:describe",
  },
  remoteBackends: {
    setToken: "remoteBackends:setToken",
    getToken: "remoteBackends:getToken",
    deleteToken: "remoteBackends:deleteToken",
  },
  localBackend: {
    getStatus: "localBackend:getStatus",
    setRemoteAccess: "localBackend:setRemoteAccess",
    setLanAccess: "localBackend:setLanAccess",
    setTailscaleHttps: "localBackend:setTailscaleHttps",
    setKeepAwakeForRemoteAccess: "localBackend:setKeepAwakeForRemoteAccess",
    rotateToken: "localBackend:rotateToken",
    createPairingCode: "localBackend:createPairingCode",
    listPairedDevices: "localBackend:listPairedDevices",
    revokePairedDevice: "localBackend:revokePairedDevice",
    // main → renderer: a phone paired, connected (last-seen), or was revoked
    pairedDevicesChanged: "localBackend:pairedDevicesChanged",
  },
  imageProxy: {
    sign: "imageProxy:sign",
  },
  issues: {
    create: "issues:create",
    delete: "issues:delete",
    getAll: "issues:getAll",
    getById: "issues:getById",
    getDetail: "issues:getDetail",
    update: "issues:update",
  },
  projects: {
    // ── lifecycle ──
    archive: "projects:archive",
    create: "projects:create",
    delete: "projects:delete",
    findByRemoteOrigin: "projects:findByRemoteOrigin",
    findOrCreate: "projects:findOrCreate",
    get: "projects:get",
    list: "projects:list",
    listBranches: "projects:listBranches",
    listByAccount: "projects:listByAccount",
    remove: "projects:remove",
    update: "projects:update",
    // ── resources ──
    addResource: "projects:addResource",
    listAvailableResources: "projects:listAvailableResources",
    listResources: "projects:listResources",
    removeResource: "projects:removeResource",
    // ── issues (via linked resources) ──
    listIssues: "projects:listIssues",
  },
  providers: {
    create: "providers:create",
    delete: "providers:delete",
    detectInstalled: "providers:detectInstalled",
    disable: "providers:disable",
    enable: "providers:enable",
    getAccountInfo: "providers:getAccountInfo",
    getAll: "providers:getAll",
    getById: "providers:getById",
    getByKind: "providers:getByKind",
    getCommands: "providers:getCommands",
    getEnabled: "providers:getEnabled",
    getModels: "providers:getModels",
    /** Push: emitted when async model-capability discovery enriches the model list. */
    modelsUpdated: "providers:modelsUpdated",
    getPlugins: "providers:getPlugins",
    getInstalledPlugins: "providers:getInstalledPlugins",
    getConnectors: "providers:getConnectors",
    startConnectorOAuth: "providers:startConnectorOAuth",
    /** Push: native connector catalog, runtime, or OAuth state changed. */
    connectorsUpdated: "providers:connectorsUpdated",
    getRateLimits: "providers:getRateLimits",
    consumeRateLimitResetCredit: "providers:consumeRateLimitResetCredit",
    /** Push: emitted when the provider streams a fresh rate-limit snapshot mid-run. */
    rateLimitsUpdated: "providers:rateLimitsUpdated",
    setGoal: "providers:setGoal",
    getGoal: "providers:getGoal",
    clearGoal: "providers:clearGoal",
    /** Push: emitted when a thread goal changes (set/updated/cleared). null goal = cleared. */
    goalUpdated: "providers:goalUpdated",
    getSkills: "providers:getSkills",
    installPlugin: "providers:installPlugin",
    readPlugin: "providers:readPlugin",
    uninstallPlugin: "providers:uninstallPlugin",
    setPluginEnabled: "providers:setPluginEnabled",
    updatePlugin: "providers:updatePlugin",
    update: "providers:update",
    /** The composer toolbar's settings as one narrow, patch-shaped write a paired device may issue. */
    updateRunSettings: "providers:updateRunSettings",
    updateCli: "providers:updateCli",
  },
  pullRequests: {
    addComment: "pullRequests:addComment",
    addReviewComment: "pullRequests:addReviewComment",
    getAvailability: "pullRequests:getAvailability",
    getDetail: "pullRequests:getDetail",
    getDiff: "pullRequests:getDiff",
    markReady: "pullRequests:markReady",
    merge: "pullRequests:merge",
    replyToThread: "pullRequests:replyToThread",
    resolveThread: "pullRequests:resolveThread",
    search: "pullRequests:search",
  },
  pulse: {
    create: "pulse:create",
    delete: "pulse:delete",
    getAll: "pulse:getAll",
    getById: "pulse:getById",
    runNow: "pulse:runNow",
    toggle: "pulse:toggle",
    update: "pulse:update",
  },
  runArtifacts: {
    add: "runArtifacts:add",
    getByRun: "runArtifacts:getByRun",
    readImage: "runArtifacts:readImage",
    remove: "runArtifacts:remove",
  },
  runContext: {
    add: "runContext:add",
    getByRun: "runContext:getByRun",
    remove: "runContext:remove",
  },
  runToolCalls: {
    getByRun: "runToolCalls:getByRun",
  },
  runTurns: {
    getByRun: "runTurns:getByRun",
    getChangesDiff: "runTurns:getChangesDiff",
    undoChanges: "runTurns:undoChanges",
  },
  runs: {
    abort: "runs:abort",
    archive: "runs:archive",
    canResume: "runs:canResume",
    cancel: "runs:cancel",
    complete: "runs:complete",
    contextUsage: "runs:contextUsage",
    continue: "runs:continue",
    create: "runs:create",
    delete: "runs:delete",
    deleteSession: "runs:deleteSession",
    diffUpdated: "runs:diffUpdated",
    ephemeralEvent: "runs:ephemeralEvent",
    eventPersisted: "runs:eventPersisted",
    execute: "runs:execute",
    executeReview: "runs:executeReview",
    fail: "runs:fail",
    fork: "runs:fork",
    getAll: "runs:getAll",
    listArchived: "runs:listArchived",
    getByAccount: "runs:getByAccount",
    getById: "runs:getById",
    getByStatus: "runs:getByStatus",
    getExecutionRoot: "runs:getExecutionRoot",
    readTextFile: "runs:readTextFile",
    getByWorkspace: "runs:getByWorkspace",
    getDetails: "runs:getDetails",
    listActive: "runs:listActive",
    listPendingApprovals: "runs:listPendingApprovals",
    listRecent: "runs:listRecent",
    moveToCollection: "runs:moveToCollection",
    start: "runs:start",
    statusChanged: "runs:statusChanged",
    toolApprovalRequest: "runs:toolApprovalRequest",
    toolApprovalResolved: "runs:toolApprovalResolved",
    toolApprovalResponse: "runs:toolApprovalResponse",
    unarchive: "runs:unarchive",
    update: "runs:update",
    updated: "runs:updated",
  },
  shell: {
    getAppsForFile: "shell:getAppsForFile",
    getInstalledApps: "shell:getInstalledApps",
    openExternal: "shell:openExternal",
    openFileWithBundle: "shell:openFileWithBundle",
    openInApp: "shell:openInApp",
    openPath: "shell:openPath",
    showItemInFolder: "shell:showItemInFolder",
  },
  signals: {
    create: "signals:create",
    delete: "signals:delete",
    getAll: "signals:getAll",
    getById: "signals:getById",
    update: "signals:update",
  },
  space: {
    archive: "space:archive",
    changed: "space:changed",
    create: "space:create",
    delete: "space:delete",
    getAll: "space:getAll",
    getById: "space:getById",
    unarchive: "space:unarchive",
    update: "space:update",
  },
  stats: {
    getDashboard: "stats:getDashboard",
  },
  sync: {
    runEntitySync: "sync:runEntitySync",
  },
  tasks: {
    create: "tasks:create",
    delete: "tasks:delete",
    getAll: "tasks:getAll",
    getById: "tasks:getById",
    update: "tasks:update",
  },
  terminal: {
    create: "terminal:create",
    data: "terminal:data",
    destroy: "terminal:destroy",
    resize: "terminal:resize",
    write: "terminal:write",
  },
  toolCalls: {
    complete: "toolCalls:complete",
    create: "toolCalls:create",
    fail: "toolCalls:fail",
    getByAccount: "toolCalls:getByAccount",
    getByRun: "toolCalls:getByRun",
    start: "toolCalls:start",
    update: "toolCalls:update",
  },
  updates: {
    check: "updates:check",
    download: "updates:download",
    getStatus: "updates:getStatus",
    quitAndInstall: "updates:quitAndInstall",
    status: "updates:status",
  },
  workspace: {
    // ── lifecycle ──
    archive: "workspace:archive",
    create: "workspace:create",
    createFromSource: "workspace:createFromSource",
    delete: "workspace:delete",
    get: "workspace:get",
    getByRootPath: "workspace:getByRootPath",
    gitStateChanged: "workspace:gitStateChanged",
    list: "workspace:list",
    listArchived: "workspace:listArchived",
    listByAccount: "workspace:listByAccount",
    listGitStates: "workspace:listGitStates",
    scriptComplete: "workspace:scriptComplete",
    selectDirectory: "workspace:selectDirectory",
    unarchive: "workspace:unarchive",
    update: "workspace:update",
    createBranch: "workspace:createBranch",
    renameBranch: "workspace:renameBranch",
    switchBranch: "workspace:switchBranch",
    discardPaths: "workspace:discardPaths",
    // ── activity ──
    createActivity: "workspace:createActivity",
    createManyActivity: "workspace:createManyActivity",
    deleteActivity: "workspace:deleteActivity",
    listActivity: "workspace:listActivity",
    // ── diffs ──
    deleteLatestDiff: "workspace:deleteLatestDiff",
    getDiffByRun: "workspace:getDiffByRun",
    getLatestDiff: "workspace:getLatestDiff",
    getLatestDiffSummary: "workspace:getLatestDiffSummary",
    listDiffs: "workspace:listDiffs",
    resyncDiff: "workspace:resyncDiff",
    // ── reviews ──
    createReview: "workspace:createReview",
    deleteReview: "workspace:deleteReview",
    getReview: "workspace:getReview",
    listReviews: "workspace:listReviews",
    updateReview: "workspace:updateReview",
    // ── findings ──
    createFinding: "workspace:createFinding",
    createManyFindings: "workspace:createManyFindings",
    deleteFinding: "workspace:deleteFinding",
    findingsChanged: "workspace:findingsChanged",
    getFinding: "workspace:getFinding",
    listFindings: "workspace:listFindings",
    listFindingsByWorkspace: "workspace:listFindingsByWorkspace",
    updateFinding: "workspace:updateFinding",
  },
} as const;
